version: '3'

services:
  lambda:
    build: .
    env_file:
      - .env.clone
    environment:
      - PYTHONPATH=/var/task:/opt/python
      - PATH=/opt/bin
    volumes:
      - ./src/:/var/task/
